name: Example - Assign Jira Version

on:
  workflow_dispatch:

jobs:
  assign-version:
    runs-on: ubuntu-latest
    steps:
      - name: Assign version to issues
        uses: ./
        with:
          jira-base-url: https://company.atlassian.net
          jira-user: ${{ secrets.JIRA_USER }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          issues: 'PROJ-1,PROJ-2,PROJ-3'
          version: 'v1.2.0'
          mode: 'fix'
          concurrency: '4'
          max-retries: '3'
